name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.x'
          channel: 'stable'
          with-web: true
          enable-web: true

      - name: Set up Flutter
        run: flutter pub global activate webdev

      - name: Install dependencies
        run: flutter pub get

      - name: Build web application
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build/web